# Generated by Django 5.2.1 on 2025-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_for_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='models_for_API.product'),
        ),
    ]
